### ISSUE TITLE
Add IPv6 Support

### ISSUE THREAD

**Issue by imadhsissou** [imadhsissou/python-arp-spoofer#1]
the current version `0.1.1` only supports `IPv4`, the tool has some functions that scans the network looking for connected hosts then forges fake `ARP` replies to intercepts packets, I used `scapy` (a packet manipulation module) and `netifaces`, it would be great if the tool supports `IPv6`.

**Comment by Germandrummer92** [comment]
IPv6 doesn't use ARP but the NDP. I will see if implementing everything is possible and refactor the codebase as well if that's okay.

**Comment by imadhsissou** [comment]
Thanks for mentioning NDP, I didn't know about it, and since it's a different protocol, I think it's a good idea to separate the implementation of ARP from NDP and allow the user to choose between two options when launching the tool eg. `--ipv4` or `--ipv6`.
