### ISSUE TITLE
CmdModule EXIT bug

### ISSUE THREAD

**Issue by imadhsissou** [imadhsissou/python-arp-spoofer#2]
I'm working with [CmdModule](https://wiki.python.org/moin/CmdModule) for writing a line-oriented command interpreter, everything is working fine except the EXIT command, when you want to exit the interpreter loop: any command that returns a true value stops the interpreter : 

```
def do_exit(self,line):
        'Close pyarp, press Ctrl+D for quick exit'
        return True
```

[full code here](https://github.com/7BISSO/python-arp-spoofer/blob/master/pyarp/pyarp.py#L196)
the Issue : I must  type `exit` command TWICE before exiting the interpreter loop successfully !!! I have no idea where the problem comes from !!!

NOTICE : It was working fine on [this point of history](https://github.com/7BISSO/python-arp-spoofer/tree/9a9c5c751c384db3b006120a5db11f2cbd196b05)

**Comment by arpit1997** [comment]
Glad to help you out. now should we close this issue?

**Comment by imadhsissou** [comment]
Yep of course !
