### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by imadhsissou** [imadhsissou/python-arp-spoofer#4]
Could be anything, adding new commands, code reformatting, improving documentation, improving performance, porting to other platforms or even rewriting in other languages ..etc :smile:, if you think you have an interesting feature please feel free to open an issue so we can discuss it before a pull request :tada: :  !

**Comment by shashankaryan** [comment]
Readme.md updated. Please review.

**Comment by imadhsissou** [comment]
Thanks a ton 👍
